/* @Trigger Name : PlanMilestoneTriggerHelper 
 * @Description  : This class is a helper class for the Milestone trigger
 * @Created By   : Gaurav Verma 
 * @Created On   : 2/12/2013
 * @Modification Log:  
 * -----------------------------------------------------------------------------
 * @Developer                Date                  Description 
 * -----------------------------------------------------------------------------
 * @Gaurav Verma           10/03/2013                Created
 * 
 * -----------------------------------------------------------------------------
 */
 
 
public with sharing class PlanMilestoneTriggerHelper {

}